In [65]:
import pandas as pd
df= pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [66]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [67]:
target= df.Survived
inputs= df.drop('Survived',axis='columns')

In [68]:
dummies= pd.get_dummies(inputs.Sex).astype(int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       0     1

In [69]:
inputs= pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age    Fare  female  male
0       3    male  34.5  7.8292       0     1
1       3  female  47.0  7.0000       1     0
2       2    male  62.0  9.6875       0     1

In [78]:
inputs.head()

   Pclass   Age     Fare  female  male
0       3  34.5   7.8292       0     1
1       3  47.0   7.0000       1     0
2       2  62.0   9.6875       0     1
3       3  27.0   8.6625       0     1
4       3  22.0  12.2875       1     0

In [79]:
#for detecting NaN values .isna() used
inputs.columns[inputs.isna().any()]

Index(['Age', 'Fare'], dtype='object')

In [80]:
inputs.Age[:20]

0     34.5
1     47.0
2     62.0
3     27.0
4     22.0
5     14.0
6     30.0
7     26.0
8     18.0
9     21.0
10     NaN
11    46.0
12    23.0
13    63.0
14    47.0
15    24.0
16    35.0
17    21.0
18    27.0
19    45.0
Name: Age, dtype: float64

In [81]:
#lets handle NaN with mean method!!
inputs.Age= inputs.Age.fillna(inputs.Age.mean())
inputs.Fare= inputs.Fare.fillna(inputs.Fare.mean())
inputs.Age[:15]
#10 is filled with 30!!

0     34.50000
1     47.00000
2     62.00000
3     27.00000
4     22.00000
5     14.00000
6     30.00000
7     26.00000
8     18.00000
9     21.00000
10    30.27259
11    46.00000
12    23.00000
13    63.00000
14    47.00000
Name: Age, dtype: float64

In [95]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(inputs,target,test_size=0.3)

In [96]:
len(X_train)

292

In [97]:
len(X_test)

126

In [98]:
len(inputs)

418

In [99]:

#lets create Naive Bayes model....
from sklearn.naive_bayes import GaussianNB
model= GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [100]:
model.score(X_test,y_test)

1.0

In [104]:
y_test[:10]

107    0
172    0
188    1
30     0
132    1
302    0
376    1
54     0
64     0
112    1
Name: Survived, dtype: int64

In [106]:
model.predict(X_test[:10])
#compare all are same soooo 1.0 is the score

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1])

In [107]:
model.predict_proba(X_test[:10])

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])