In [28]:
import pandas as pd
import numpy as np

In [30]:
df= pd.read_csv("emailspam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [31]:
df.Category.value_counts()

Category
ham               4825
spam               747
{"mode":"full"       1
Name: count, dtype: int64

In [32]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [33]:
df.shape

(5573, 3)

In [34]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [36]:
X_train.shape

(4458,)

In [37]:
X_test.shape

(1115,)

In [38]:
type(X_train)

pandas.core.series.Series

In [39]:
X_train[:4]

2052    Hey darlin.. i can pick u up at college if u t...
137                    He is there. You call and meet him
1397                             Shall i start from hear.
1905    Wah... Okie okie... Muz make use of e unlimite...
Name: Message, dtype: object

In [40]:
#CREATING BAG OF WORDS USING CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59367 stored elements and shape (4458, 7697)>

In [41]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
X_train_cv.shape

(4458, 7697)

In [43]:
v.vocabulary_

{'hey': 3385,
 'darlin': 2152,
 'can': 1618,
 'pick': 5160,
 'up': 7137,
 'at': 1109,
 'college': 1879,
 'if': 3566,
 'tell': 6710,
 'me': 4359,
 'wen': 7402,
 'where': 7428,
 'mt': 4574,
 'love': 4186,
 'pete': 5128,
 'xx': 7603,
 'he': 3331,
 'is': 3713,
 'there': 6787,
 'you': 7657,
 'call': 1596,
 'and': 954,
 'meet': 4377,
 'him': 3400,
 'shall': 6020,
 'start': 6397,
 'from': 2985,
 'hear': 3341,
 'wah': 7301,
 'okie': 4872,
 'muz': 4613,
 'make': 4282,
 'use': 7172,
 'of': 4841,
 'unlimited': 7125,
 'haha': 3260,
 'men': 4397,
 'always': 925,
 'needs': 4680,
 'beautiful': 1269,
 'intelligent': 3669,
 'caring': 1648,
 'loving': 4196,
 'adjustable': 806,
 'cooperative': 1992,
 'wife': 7456,
 'but': 1566,
 'the': 6771,
 'law': 4002,
 'allows': 911,
 'only': 4894,
 'one': 4888,
 'still': 6434,
 'havent': 3323,
 'collected': 1875,
 'dough': 2411,
 'pls': 5219,
 'let': 4047,
 'know': 3927,
 'so': 6232,
 'go': 3125,
 'to': 6891,
 'place': 5188,
 'sent': 5977,
 'it': 3723,
 'get': 3082,
 'control': 1977,
 'number': 4805,
 'lol': 4142,
 'they': 6794,
 'were': 7406,
 'mad': 4256,
 'first': 2841,
 'then': 6783,
 'woke': 7519,
 'gave': 3055,
 'in': 3608,
 'watching': 7351,
 'tv': 7039,
 'now': 4790,
 'got': 3164,
 'new': 4707,
 'job': 3797,
 'machan': 4252,
 'gym': 3250,
 'tomorrow': 6918,
 'wil': 7461,
 'come': 1890,
 'late': 3990,
 'goodnight': 3153,
 'hope': 3455,
 'are': 1042,
 'having': 3326,
 'good': 3148,
 'week': 7385,
 'just': 3845,
 'checking': 1743,
 'this': 6809,
 'much': 4584,
 'buzy': 1575,
 've': 7214,
 'told': 6907,
 'that': 6767,
 'returned': 5728,
 'should': 6076,
 're': 5555,
 'order': 4930,
 'sorry': 6278,
 'chikku': 1767,
 'my': 4616,
 'cell': 1694,
 'some': 6246,
 'problem': 5395,
 'thts': 6839,
 'was': 7340,
 'nt': 4796,
 'able': 743,
 'reply': 5680,
 'or': 4922,
 'msg': 4566,
 'not': 4777,
 'directly': 2320,
 'behind': 1299,
 'abt': 753,
 'rows': 5795,
 'sick': 6105,
 'needy': 4681,
 'want': 7327,
 'pouts': 5307,
 'stomps': 6441,
 'feet': 2785,
 'slave': 6170,
 'soon': 6270,
 'will': 7465,
 'have': 3320,
 'real': 5566,
 'thing': 6798,
 'princess': 5381,
 'do': 2361,
 'wet': 7417,
 'hello': 3362,
 'how': 3487,
 'goes': 3132,
 'day': 2167,
 'wish': 7486,
 'your': 7662,
 'well': 7399,
 'fine': 2828,
 'babe': 1179,
 'find': 2825,
 'prospects': 5430,
 'miss': 4459,
 'boytoy': 1464,
 'teasing': 6698,
 'kiss': 3917,
 'erm': 2607,
 'ill': 3578,
 'about': 745,
 '45pm': 490,
 'll': 4118,
 'give': 3107,
 'enough': 2584,
 'time': 6858,
 'park': 5038,
 'noe': 4744,
 'did': 2286,
 'specify': 6315,
 'da': 2130,
 'domain': 2386,
 'as': 1078,
 'nusstu': 4811,
 'sch': 5899,
 'subscribed': 6512,
 'best': 1319,
 'mobile': 4492,
 'content': 1968,
 'service': 5990,
 'uk': 7076,
 'for': 2909,
 'per': 5100,
 '10': 249,
 'days': 2168,
 'until': 7136,
 'send': 5969,
 'stop': 6446,
 '82324': 644,
 'helpline': 3370,
 '08706091795': 80,
 'complain': 1911,
 'num': 4804,
 'bettr': 1326,
 'bsnl': 1526,
 'offc': 4844,
 'nd': 4664,
 'apply': 1017,
 'called': 1602,
 'no': 4740,
 'phone': 5145,
 'ask': 1087,
 'both': 1435,
 'them': 6780,
 'already': 916,
 'said': 5842,
 'ok': 4867,
 'thank': 6758,
 'baby': 1182,
 'cant': 1629,
 'wait': 7307,
 'taste': 6667,
 'moby': 4500,
 'pub': 5449,
 'quiz': 5502,
 'win': 7468,
 '100': 250,
 'high': 3394,
 'street': 6464,
 'prize': 5389,
 'who': 7440,
 'duchess': 2458,
 'cornwall': 1999,
 'be': 1264,
 'txt': 7050,
 'her': 3377,
 'name': 4634,
 '82277': 643,
 'unsub': 7132,
 '50': 523,
 '008704050406': 3,
 'sp': 6296,
 'arrow': 1071,
 '545': 538,
 'lor': 4164,
 'ya': 7615,
 'dinner': 2315,
 'together': 6901,
 'what': 7420,
 'type': 7062,
 'food': 2900,
 'like': 4071,
 'buy': 1571,
 'egg': 2525,
 'please': 5211,
 'too': 6931,
 'early': 2488,
 'project': 5410,
 'meeting': 4379,
 'sexy': 6006,
 'cum': 2101,
 'text': 6741,
 'im': 3582,
 'warm': 7334,
 'ready': 5565,
 'porn': 5275,
 'fun': 3009,
 'free': 2952,
 'recd': 5587,
 'msgs': 4572,
 '150p': 296,
 'inc': 3610,
 'vat': 7210,
 'cancel': 1621,
 'goodmorning': 3152,
 'sleeping': 6173,
 'ga': 3027,
 'leaving': 4024,
 'house': 3482,
 'eatin': 2501,
 'later': 3993,
 'wif': 7455,
 'frens': 2963,
 'lei': 4034,
 'going': 3137,
 'home': 3437,
 'lt': 4209,
 'gt': 3224,
 'ish': 3716,
 'minutes': 4450,
 'ago': 860,
 'wtf': 7582,
 'urgent': 7157,
 'we': 7363,
 '800': 621,
 'flights': 2865,
 'europe': 2633,
 'away': 1164,
 'b4': 1174,
 '10th': 261,
 'sept': 5982,
 'take': 6644,
 'friend': 2971,
 'claim': 1807,
 'on': 4884,
 '09050000555': 157,
 'ba128nnfwfly150ppm': 1177,
 'short': 6068,
 'cute': 2120,
 'person': 5119,
 'dont': 2391,
 'try': 7016,
 'prove': 5432,
 'gud': 3229,
 'mrng': 4563,
 'yar': 7620,
 'say': 5886,
 'error': 2611,
 'dear': 2179,
 'bus': 1559,
 'calicut': 1594,
 'when': 7424,
 'wana': 7325,
 'see': 5944,
 'office': 4852,
 'min': 4432,
 'am': 927,
 'very': 7226,
 'entertaining': 2589,
 'getting': 3089,
 'whole': 7442,
 'hugh': 3510,
 'laurie': 4001,
 'even': 2636,
 'with': 7494,
 'stick': 6432,
 'indeed': 3625,
 'especially': 2622,
 'exe': 2677,
 'mail': 4274,
 'id': 3554,
 'yup': 7682,
 'right': 5746,
 'back': 1188,
 'yes': 7640,
 'town': 6959,
 'exciting': 2673,
 'adult': 820,
 'singles': 6133,
 'chat': 1730,
 '86688': 673,
 'explicit': 2697,
 'sex': 6002,
 '30': 413,
 'secs': 5940,
 'ring': 5752,
 '02073162414': 12,
 'costs': 2011,
 '20p': 344,
 'gsex': 3223,
 'pobox': 5228,
 '2667': 363,
 'wc1n': 7361,
 '3xx': 463,
 'oh': 4862,
 'kay': 3873,
 'sat': 5870,
 'promise': 5415,
 'care': 1639,
 'run': 5818,
 'pics': 5164,
 'chance': 1708,
 'ttyl': 7025,
 'password': 5058,
 'address': 803,
 'sir': 6138,
 'giving': 3110,
 'second': 5934,
 'rahul': 5515,
 'dengra': 2233,
 'en': 2561,
 'nange': 4642,
 'bakra': 1201,
 'kalstiya': 3862,
 'had': 3257,
 'tea': 6687,
 'coffee': 1864,
 'normal': 4769,
 'pilates': 5174,
 'after': 844,
 'our': 4956,
 'intro': 3682,
 'yo': 7652,
 'guess': 3233,
 'dropped': 2441,
 'ugh': 7072,
 'don': 2387,
 'wanna': 7326,
 'out': 4959,
 'bed': 1278,
 'sure': 6580,
 'finish': 2831,
 'spend': 6325,
 'evening': 2637,
 'cos': 2007,
 'would': 7559,
 'vewy': 7228,
 'lubly': 4213,
 'xxx': 7606,
 'last': 3988,
 'ur': 7154,
 '150': 294,
 'worth': 7555,
 'discount': 2336,
 'vouchers': 7280,
 '85023': 665,
 'savamob': 5880,
 'member': 4392,
 'offers': 4851,
 'cs': 2082,
 '08717898035': 127,
 '00': 0,
 'sub': 6503,
 '16': 306,
 'remove': 5663,
 'yetunde': 7645,
 'hasn': 3309,
 'money': 4517,
 'yet': 7643,
 'bother': 1436,
 'sending': 5971,
 'its': 3731,
 'over': 4974,
 'involve': 3694,
 'yourself': 7667,
 'anything': 995,
 'shouldn': 6077,
 'imposed': 3600,
 'apologise': 1007,
 'joy': 3823,
 'father': 2760,
 'john': 3804,
 '____': 726,
 'ans': 974,
 'ths': 6837,
 'hav': 3317,
 'iq': 3703,
 'tis': 6870,
 'ias': 3541,
 'question': 5492,
 'answer': 976,
 'awake': 1161,
 'depends': 2240,
 '1st': 325,
 'ringtone': 5755,
 'tone': 6920,
 'gr8': 3176,
 'top': 6939,
 '20': 333,
 'tones': 6921,
 'every': 2643,
 'wk': 7504,
 'opt': 4917,
 '08452810071': 63,
 'usually': 7184,
 'unconscious': 7094,
 'children': 1771,
 'adults': 821,
 'may': 4350,
 'behave': 1298,
 'abnormally': 744,
 'parents': 5035,
 'kidz': 3901,
 'friends': 2972,
 'colleagues': 1873,
 'all': 903,
 'screaming': 5918,
 'surprise': 6585,
 'waiting': 7310,
 'sofa': 6235,
 'naked': 4632,
 'de': 2173,
 'webadres': 7373,
 'geting': 3085,
 'salary': 5846,
 'slip': 6182,
 'smsservices': 6215,
 'yourinclusive': 7664,
 'credits': 2060,
 'goto': 3168,
 'www': 7590,
 'comuk': 1927,
 'net': 4692,
 'login': 4138,
 '3qxj9': 458,
 'unsubscribe': 7133,
 'extra': 2707,
 'charge': 1720,
 'help': 3365,
 '08702840625': 77,
 '220': 349,
 'cm2': 1846,
 '9ae': 720,
 'dude': 2460,
 'longer': 4150,
 'pisces': 5180,
 'an': 950,
 'aquarius': 1036,
 'class': 1814,
 'water': 7352,
 'training': 6969,
 'manual': 4304,
 'show': 6082,
 'tech': 6699,
 'process': 5400,
 'reset': 5698,
 'troubleshooting': 7005,
 'huh': 3512,
 'fr': 2942,
 'knows': 3930,
 'ain': 871,
 'smokin': 6209,
 'subscriber': 6513,
 'draw': 2424,
 'gift': 3095,
 'voucher': 7279,
 'entered': 2586,
 'receipt': 5588,
 'correct': 2002,
 'elvis': 2548,
 'presleys': 5360,
 'birthday': 1356,
 '80062': 623,
 'thinl': 6806,
 'role': 5776,
 'sachin': 5834,
 'standing': 6389,
 'others': 4951,
 'hit': 3406,
 'apparently': 1011,
 'bffs': 1332,
 'carly': 1651,
 'quick': 5495,
 'coughing': 2017,
 'nothing': 4782,
 'since': 6126,
 'talk': 6652,
 'boston': 1433,
 'personal': 5120,
 'statement': 6406,
 'woulda': 7560,
 'changed': 1711,
 'realized': 5573,
 'nyc': 4819,
 'says': 5889,
 'eh': 2527,
 'den': 2231,
 'book': 1415,
 'kb': 3875,
 'liao': 4053,
 'doing': 2378,
 'test': 6735,
 'earlier': 2486,
 'appreciate': 1021,
 'aight': 870,
 'wat': 7346,
 'happening': 3291,
 'side': 6107,
 'been': 1283,
 'specially': 6313,
 'selected': 5956,
 'receive': 5590,
 '3000': 415,
 'award': 1162,
 '08712402050': 98,
 'before': 1289,
 'lines': 4088,
 'close': 1832,
 'cost': 2008,
 '10ppm': 260,
 'ag': 850,
 'promo': 5417,
 'might': 4425,
 'any': 987,
 'teach': 6688,
 'ship': 6047,
 'cars': 1657,
 'bath': 1239,
 'key': 3887,
 'window': 7470,
 'play': 5202,
 'computer': 1924,
 'aiyah': 878,
 'tok': 6904,
 'wow': 7562,
 'sooo': 6273,
 'barely': 1223,
 'stand': 6387,
 'wonder': 7526,
 'think': 6800,
 'lar': 3982,
 'nydc': 4820,
 'wheellock': 7423,
 'helloooo': 3364,
 'wake': 7311,
 'sweet': 6606,
 'morning': 4536,
 'welcomes': 7398,
 'enjoy': 2577,
 'full': 3006,
 'literally': 4109,
 'hours': 3481,
 'purity': 5466,
 'friendship': 2974,
 'between': 1327,
 'two': 7048,
 'smiling': 6204,
 'reading': 5564,
 'forwarded': 2933,
 'message': 4409,
 'by': 1580,
 'seeing': 5946,
 'evng': 2657,
 'musthu': 4610,
 'fear': 2772,
 'fainting': 2729,
 'housework': 3485,
 'cuppa': 2106,
 '09066612661': 231,
 'landline': 3970,
 'complementary': 1914,
 'tenerife': 6722,
 'holiday': 3432,
 '000': 1,
 'cash': 1661,
 'await': 1159,
 'collection': 1877,
 'sae': 5837,
 'po': 5227,
 'box': 1445,
 'wa14': 7297,
 '2px': 400,
 '150ppm': 300,
 '18': 311,
 'sender': 5970,
 'hol': 3426,
 'offer': 4848,
 'looking': 4156,
 'car': 1635,
 'gone': 3144,
 '4the': 513,
 'driving': 2438,
 'mah': 4270,
 'night': 4723,
 'sleepwell': 6175,
 'amp': 943,
 'took': 6932,
 'tablets': 6634,
 'reaction': 5561,
 'mm': 4479,
 'di': 2276,
 'gonna': 3146,
 'comes': 1892,
 'bak': 1200,
 'coming': 1895,
 't4get2text': 6629,
 'dis': 2325,
 'wit': 7493,
 'different': 2299,
 'actually': 794,
 'decided': 2190,
 'hungry': 3520,
 'haven': 3322,
 'left': 4027,
 'grandfather': 3185,
 'expired': 2694,
 'leave': 4022,
 'today': 6897,
 'al': 885,
 'above': 747,
 '2nd': 394,
 'tried': 6997,
 'contact': 1964,
 'won': 7524,
 '750': 602,
 'pound': 5302,
 'easy': 2498,
 '08718726970': 134,
 '10p': 259,
 'bt': 1528,
 'national': 4654,
 'rate': 5540,
 'need': 4676,
 'hotel': 3475,
 'invitation': 3688,
 'cali': 1593,
 'english': 2576,
 'bloke': 1386,
 'weddin': 7378,
 'never': 4703,
 'bloomberg': 1391,
 'center': 1696,
 '447797706009': 482,
 'why': 7448,
 'future': 3021,
 'http': 3502,
 'careers': 1643,
 'com': 1884,
 'plumbers': 5220,
 'tape': 6664,
 'wrench': 7565,
 'could': 2018,
 'borrow': 1431,
 'dunno': 2470,
 'dat': 2158,
 'thanks': 6759,
 'picking': 5162,
 'trash': 6982,
 'awarded': 1163,
 '2000': 335,
 'bonus': 1413,
 'caller': 1603,
 '03': 15,
 'final': 2820,
 '09064019788': 208,
 'box42wr29c': 1456,
 'okay': 4868,
 'ah': 862,
 'persons': 5123,
 'story': 6457,
 'made': 4260,
 'eta': 2626,
 'taunton': 6675,
 '12': 271,
 'planned': 5197,
 'okday': 4869,
 'anyway': 997,
 'space': 6297,
 'invaders': 3684,
 'orig': 4940,
 'arcade': 1040,
 'game': 3037,
 'console': 1961,
 'press': 5362,
 'games': 3038,
 'std': 6415,
 'wap': 7332,
 'o2': 4824,
 'co': 1852,
 'terms': 6727,
 'settings': 5996,
 'purchase': 5464,
 'important': 3598,
 'information': 3641,
 'orange': 4926,
 'user': 7176,
 '0789xxxxxxx': 37,
 'lucky': 4216,
 '2find': 376,
 'log': 4137,
 'onto': 4897,
 'urawinner': 7155,
 'fantastic': 2748,
 'awaiting': 1160,
 'fried': 2970,
 'essential': 2625,
 'part': 5042,
 'keep': 3877,
 'spares': 6304,
 'because': 1273,
 'fucking': 2998,
 'idiot': 3562,
 'roommates': 5785,
 'looovvve': 4160,
 'running': 5819,
 'lunch': 4221,
 'online': 4892,
 'dog': 2373,
 'hanging': 3285,
 'brother': 1514,
 'his': 3404,
 'family': 2742,
 'happy': 3297,
 'years': 7630,
 'melody': 4390,
 'thk': 6810,
 'juz': 3851,
 'accordin': 771,
 'discussed': 2339,
 'yest': 7641,
 'except': 2671,
 'sun': 6554,
 'lesson': 4045,
 'attend': 1120,
 'bags': 1196,
 'blanket': 1371,
 'paper': 5023,
 'details': 2260,
 'else': 2546,
 'entirely': 2591,
 'understood': 7102,
 'ho': 3423,
 'which': 7434,
 'weekend': 7386,
 'emailed': 2551,
 'yifeng': 7648,
 'oredi': 4934,
 'link': 4091,
 'picture': 5166,
 'has': 3307,
 'also': 919,
 'alto18': 922,
 'wave': 7357,
 'asp': 1095,
 '44345': 481,
 'watch': 7347,
 'saw': 5885,
 'few': 2795,
 'swatch': 6600,
 'quite': 5499,
 'ard': 1041,
 '116': 267,
 'opinion': 4911,
 'leh': 4033,
 'vote': 7277,
 'wherever': 7430,
 'heart': 3345,
 'guides': 3239,
 'aww': 1167,
 'must': 4608,
 'nearly': 4670,
 'dead': 2174,
 'jez': 3789,
 'iscoming': 3715,
 'todo': 6899,
 'workand': 7542,
 'whilltake': 7436,
 'forever': 2913,
 'near': 4667,
 'campus': 1616,
 'bank': 1214,
 'granite': 3188,
 'issues': 3721,
 'strong': 6477,
 'explosive': 2699,
 'members': 4393,
 '300': 414,
 'nasdaq': 4646,
 'symbol': 6623,
 'cdgt': 1686,
 'speak': 6308,
 'hmm': 3416,
 'email': 2550,
 'double': 2406,
 'eviction': 2655,
 'spiral': 6335,
 'michael': 4421,
 'riddance': 5744,
 'thanx': 6764,
 'gd': 3062,
 'nite': 4733,
 'alive': 902,
 'better': 1325,
 'figure': 2811,
 'itself': 3732,
 'life': 4061,
 'diet': 2293,
 'ate': 1110,
 'many': 4305,
 'slices': 6178,
 'pizza': 5187,
 'yesterday': 7642,
 'dun': 2468,
 'wan': 7323,
 'infernal': 3637,
 'affair': 832,
 'making': 4286,
 'pay': 5070,
 'yrs': 7673,
 'god': 3131,
 'taken': 6646,
 'teeth': 6704,
 'paining': 5006,
 'room': 5782,
 'hadn': 3258,
 'put': 5474,
 'clocks': 1830,
 'til': 6855,
 'shouted': 6078,
 'everyone': 2647,
 'realised': 5569,
 'wahay': 7302,
 'another': 973,
 'hour': 3480,
 'customer': 2115,
 'representative': 5684,
 '0800': 41,
 '169': 309,
 '6031': 555,
 '10am': 257,
 '9pm': 723,
 'guaranteed': 3227,
 '1000': 251,
 '5000': 525,
 'afternoon': 846,
 'sighs': 6109,
 'nitros': 4735,
 'hurry': 3526,
 'crash': 2048,
 'pretty': 5369,
 'weak': 7364,
 'bad': 1191,
 'hot': 3474,
 'horny': 3464,
 'willing': 7466,
 'live': 4111,
 'local': 4129,
 'strt': 6478,
 'netcollex': 4693,
 'ltdhelpdesk': 4211,
 '02085076972': 13,
 'end': 2562,
 'size': 6152,
 'elephant': 2543,
 'shove': 6080,
 'um': 7082,
 'ass': 1097,
 'work': 7540,
 'maybe': 4352,
 'didn': 2288,
 'messages': 4411,
 'glo': 3115,
 'carlos': 1650,
 'down': 2412,
 'swing': 6614,
 'usf': 7178,
 'little': 4110,
 'bit': 1358,
 'yeah': 7628,
 'started': 6398,
 'same': 5857,
 'stuff': 6492,
 'dull': 2465,
 'guys': 3247,
 'nice': 4716,
 'off': 4843,
 'sheffield': 6034,
 'tom': 6912,
 'air': 873,
 'opinions': 4912,
 'categories': 1674,
 'used': 7173,
 'measure': 4368,
 'ethnicity': 2628,
 'next': 4713,
 'census': 1695,
 'busy': 1565,
 'transcribing': 6975,
 'hmmm': 3417,
 'thought': 6820,
 'punish': 5459,
 'spirit': 6336,
 'bb': 1248,
 'trying': 7017,
 'byatch': 1581,
 'whassup': 7419,
 'holla': 3433,
 'whenever': 7425,
 'around': 1062,
 'excuse': 2674,
 'creep': 2061,
 'people': 5098,
 'sarasota': 5865,
 'bomb': 1411,
 'date': 2160,
 'wanted': 7329,
 'conference': 1940,
 'haf': 3259,
 'eaten': 2500,
 'calling': 1607,
 'tension': 6724,
 'face': 2715,
 'waste': 7344,
 'innocent': 3653,
 'terror': 6732,
 'cruel': 2076,
 'romantic': 5779,
 'lovable': 4185,
 'decent': 2188,
 'joker': 3809,
 'happens': 3292,
 'vegas': 7215,
 'stays': 6414,
 'great': 3200,
 'church': 1800,
 'surfing': 6582,
 'surely': 6581,
 'forgot': 2921,
 'touch': 6954,
 'eyes': 2712,
 'vava': 7212,
 'playing': 5207,
 'umma': 7083,
 'onluy': 4893,
 'matters': 4342,
 'offcampus': 4845,
 'tessy': 6734,
 'favor': 2767,
 'convey': 1981,
 'wishes': 7488,
 'nimya': 4730,
 'dnt': 2360,
 'forget': 2916,
 ...}

In [44]:
v.get_feature_names_out()[4186]

'love'

In [45]:

X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
np.where(X_train_np[0]!=0)

(array([1109, 1618, 1879, 2152, 3385, 3566, 4186, 4359, 4574, 5128, 5160,
        6710, 7137, 7402, 7428, 7603], dtype=int64),)

In [49]:
X_train_np[0][4186]

1

In [50]:
#TRAINING Naive Bayes Model

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [51]:
X_test_cv = v.transform(X_test)

In [52]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       971
           1       0.96      0.90      0.93       144

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [53]:

emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)