In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

   age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              1                 1
4   46              1                 1

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df[['age','affordability']],df.bought_insurance,test_size=0.2,random_state=25)

In [4]:
len(X_train)

20

In [5]:
X_train_scaled= X_train.copy()
X_train_scaled['age']= X_train_scaled['age']/100

X_test_scaled= X_test.copy()
X_test_scaled['age']= X_test_scaled['age']/100

In [6]:
X_train_scaled

     age  affordability
0   0.22              1
13  0.49              1
6   0.60              1
17  0.19              1
23  0.50              1
19  0.21              1
24  0.54              0
16  0.58              1
20  0.26              0
3   0.52              1
7   0.62              0
1   0.25              0
5   0.55              0
25  0.23              1
8   0.61              0
18  0.18              0
12  0.29              1
22  0.45              1
15  0.25              0
4   0.46              1

In [7]:

model = keras.Sequential([
    keras.layers.Dense(
        1,
        input_shape=(2,),       
        activation='sigmoid',
        kernel_initializer='ones',
        bias_initializer='zeros'
    )
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scaled,y_train,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 238ms/step - loss: 0.7634 - accuracy: 0.4000
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7629 - accuracy: 0.4000
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7624 - accuracy: 0.4000
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7618 - accuracy: 0.4000
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7613 - accuracy: 0.4000
Epoch 6/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7608 - accuracy: 0.4000
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7603 - accuracy: 0.4000
Epoch 8/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7598 - accuracy: 0.4000
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7593 - accuracy: 0.4000
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7588 - accuracy: 0.4000
Epoch 11/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7583 - accuracy: 0.4000
Epoch 12/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7578 - accuracy: 0.4000
Epoch 13/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7572 - accuracy: 0.4000
Epoch 14/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7567 - accuracy: 0.4000
Epoch 15/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7562 - accuracy: 0.4000
Epoch 16/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7557 - accuracy: 0.4000
Epoch 17/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7552 - accuracy: 0.4000
Epoch 18/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7547 - accuracy: 0.4000
Epoch 19/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7542 - accuracy: 0.4000
Epoch 20/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7537 - accuracy: 0.4000
Epoch 21/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7532 - accuracy: 0.4000
Epoch 22/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7527 - accuracy: 0.4000
Epoch 23/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7522 - accuracy: 0.4000
Epoch 24/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7517 - accuracy: 0.4000
Epoch 25/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7512 - accuracy: 0.4000
Epoch 26/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7507 - accuracy: 0.4000
Epoch 27/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7502 - accuracy: 0.4000
Epoch 28/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7497 - accuracy: 0.4000
Epoch 29/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7493 - accuracy: 0.4000
Epoch 30/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7488 - accuracy: 0.4000
Epoch 31/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7483 - accuracy: 0.4000
Epoch 32/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7478 - accuracy: 0.4000
Epoch 33/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7473 - accuracy: 0.4000
Epoch 34/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7468 - accuracy: 0.4000
Epoch 35/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7463 - accuracy: 0.4000
Epoch 36/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7458 - accuracy: 0.4000
Epoch 37/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7454 - accuracy: 0.4000
Epoch 38/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7449 - accuracy: 0.4000
Epoch 39/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7444 - accuracy: 0.4000
Epoch 40/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7439 - accuracy: 0.4000
Epoch 41/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7434 - accuracy: 0.4000
Epoch 42/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7430 - accuracy: 0.4000
Epoch 43/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7425 - accuracy: 0.4000
Epoch 44/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7420 - accuracy: 0.4000
Epoch 45/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7415 - accuracy: 0.4000
Epoch 46/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7410 - accuracy: 0.4000
Epoch 47/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7406 - accuracy: 0.4000
Epoch 48/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7401 - accuracy: 0.4000
Epoch 49/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7396 - accuracy: 0.4000
Epoch 50/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7392 - accuracy: 0.4000
Epoch 51/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7387 - accuracy: 0.4000
Epoch 52/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7382 - accuracy: 0.4000
Epoch 53/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7378 - accuracy: 0.4000
Epoch 54/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7373 - accuracy: 0.4000
Epoch 55/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7368 - accuracy: 0.4000
Epoch 56/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7364 - accuracy: 0.4000
Epoch 57/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7359 - accuracy: 0.4000
Epoch 58/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7354 - accuracy: 0.4000
Epoch 59/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7350 - accuracy: 0.4000
Epoch 60/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7345 - accuracy: 0.4000
Epoch 61/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7341 - accuracy: 0.4000
Epoch 62/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7336 - accuracy: 0.4000
Epoch 63/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7332 - accuracy: 0.4000
Epoch 64/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7327 - accuracy: 0.4000
Epoch 65/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7322 - accuracy: 0.4000
Epoch 66/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7318 - accuracy: 0.4000
Epoch 67/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7313 - accuracy: 0.4000
Epoch 68/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7309 - accuracy: 0.4000
Epoch 69/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7304 - accuracy: 0.4000
Epoch 70/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7300 - accuracy: 0.4000
Epoch 71/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7296 - accuracy: 0.4000
Epoch 72/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7291 - accuracy: 0.4000
Epoch 73/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7287 - accuracy: 0.4000
Epoch 74/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7282 - accuracy: 0.4000
Epoch 75/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7278 - accuracy: 0.4000
Epoch 76/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7273 - accuracy: 0.4000
Epoch 77/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7269 - accuracy: 0.4000
Epoch 78/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7265 - accuracy: 0.4000
Epoch 79/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7260 - accuracy: 0.4000
Epoch 80/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7256 - accuracy: 0.4000
Epoch 81/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7251 - accuracy: 0.4000
Epoch 82/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7247 - accuracy: 0.4000
Epoch 83/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7243 - accuracy: 0.4000
Epoch 84/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7238 - accuracy: 0.4000
Epoch 85/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7234 - accuracy: 0.4000
Epoch 86/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7230 - accuracy: 0.4000
Epoch 87/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7225 - accuracy: 0.4000
Epoch 88/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7221 - accuracy: 0.4000
Epoch 89/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7217 - accuracy: 0.4000
Epoch 90/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7213 - accuracy: 0.4000
Epoch 91/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7208 - accuracy: 0.4000
Epoch 92/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7204 - accuracy: 0.4000
Epoch 93/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7200 - accuracy: 0.4000
Epoch 94/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7196 - accuracy: 0.4000
Epoch 95/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7192 - accuracy: 0.4000
Epoch 96/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7187 - accuracy: 0.4000
Epoch 97/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7183 - accuracy: 0.4000
Epoch 98/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7179 - accuracy: 0.4000
Epoch 99/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7175 - accuracy: 0.4000
Epoch 100/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7171 - accuracy: 0.4000
Epoch 101/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7166 - accuracy: 0.4000
Epoch 102/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7162 - accuracy: 0.4000
Epoch 103/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7158 - accuracy: 0.4000
Epoch 104/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7154 - accuracy: 0.4000
Epoch 105/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7150 - accuracy: 0.4000
Epoch 106/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7146 - accuracy: 0.4000
Epoch 107/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7142 - accuracy: 0.4000
Epoch 108/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7138 - accuracy: 0.4000
Epoch 109/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7134 - accuracy: 0.4000
Epoch 110/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7130 - accuracy: 0.4000
Epoch 111/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7126 - accuracy: 0.4000
Epoch 112/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7122 - accuracy: 0.4000
Epoch 113/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7118 - accuracy: 0.4000
Epoch 114/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7114 - accuracy: 0.4000
Epoch 115/500
1/1 [==============================] - 0s 0s/step - loss: 0.7110 - accuracy: 0.4000
Epoch 116/500
1/1 [==============================] - 0s 13ms/step - loss: 0.7106 - accuracy: 0.4000
Epoch 117/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7102 - accuracy: 0.4000
Epoch 118/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7098 - accuracy: 0.4000
Epoch 119/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7094 - accuracy: 0.4000
Epoch 120/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7090 - accuracy: 0.4000
Epoch 121/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7086 - accuracy: 0.4000
Epoch 122/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7082 - accuracy: 0.4000
Epoch 123/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7078 - accuracy: 0.4000
Epoch 124/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7074 - accuracy: 0.4000
Epoch 125/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7070 - accuracy: 0.4000
Epoch 126/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7066 - accuracy: 0.4000
Epoch 127/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7062 - accuracy: 0.4000
Epoch 128/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7058 - accuracy: 0.4000
Epoch 129/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7055 - accuracy: 0.4000
Epoch 130/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7051 - accuracy: 0.4000
Epoch 131/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7047 - accuracy: 0.4000
Epoch 132/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7043 - accuracy: 0.4000
Epoch 133/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7039 - accuracy: 0.4000
Epoch 134/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7035 - accuracy: 0.4000
Epoch 135/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7032 - accuracy: 0.4000
Epoch 136/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7028 - accuracy: 0.4000
Epoch 137/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7024 - accuracy: 0.4000
Epoch 138/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7020 - accuracy: 0.4000
Epoch 139/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7017 - accuracy: 0.4000
Epoch 140/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7013 - accuracy: 0.4000
Epoch 141/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7009 - accuracy: 0.4000
Epoch 142/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7005 - accuracy: 0.4000
Epoch 143/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7002 - accuracy: 0.4000
Epoch 144/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6998 - accuracy: 0.4000
Epoch 145/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6994 - accuracy: 0.4000
Epoch 146/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6991 - accuracy: 0.4000
Epoch 147/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6987 - accuracy: 0.4000
Epoch 148/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6983 - accuracy: 0.4000
Epoch 149/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6980 - accuracy: 0.4000
Epoch 150/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6976 - accuracy: 0.4000
Epoch 151/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6972 - accuracy: 0.4000
Epoch 152/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6969 - accuracy: 0.4000
Epoch 153/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6965 - accuracy: 0.4000
Epoch 154/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6961 - accuracy: 0.4000
Epoch 155/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6958 - accuracy: 0.4000
Epoch 156/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6954 - accuracy: 0.4000
Epoch 157/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6951 - accuracy: 0.4000
Epoch 158/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6947 - accuracy: 0.4000
Epoch 159/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6944 - accuracy: 0.4000
Epoch 160/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6940 - accuracy: 0.4500
Epoch 161/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6936 - accuracy: 0.4500
Epoch 162/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6933 - accuracy: 0.4500
Epoch 163/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6929 - accuracy: 0.4500
Epoch 164/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6926 - accuracy: 0.4500
Epoch 165/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6922 - accuracy: 0.4500
Epoch 166/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6919 - accuracy: 0.4500
Epoch 167/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6915 - accuracy: 0.4500
Epoch 168/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6912 - accuracy: 0.4500
Epoch 169/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6909 - accuracy: 0.4500
Epoch 170/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6905 - accuracy: 0.4500
Epoch 171/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6902 - accuracy: 0.4500
Epoch 172/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6898 - accuracy: 0.4500
Epoch 173/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6895 - accuracy: 0.4500
Epoch 174/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6891 - accuracy: 0.4500
Epoch 175/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6888 - accuracy: 0.4500
Epoch 176/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6885 - accuracy: 0.4500
Epoch 177/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6881 - accuracy: 0.4500
Epoch 178/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6878 - accuracy: 0.4500
Epoch 179/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6874 - accuracy: 0.4500
Epoch 180/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6871 - accuracy: 0.4500
Epoch 181/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6868 - accuracy: 0.4500
Epoch 182/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6864 - accuracy: 0.4500
Epoch 183/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.4500
Epoch 184/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6858 - accuracy: 0.4500
Epoch 185/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6854 - accuracy: 0.4500
Epoch 186/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6851 - accuracy: 0.4500
Epoch 187/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6848 - accuracy: 0.4500
Epoch 188/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6845 - accuracy: 0.4500
Epoch 189/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6841 - accuracy: 0.4500
Epoch 190/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6838 - accuracy: 0.4500
Epoch 191/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6835 - accuracy: 0.4500
Epoch 192/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6831 - accuracy: 0.4500
Epoch 193/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6828 - accuracy: 0.4500
Epoch 194/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6825 - accuracy: 0.4500
Epoch 195/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6822 - accuracy: 0.4500
Epoch 196/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6819 - accuracy: 0.4500
Epoch 197/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6815 - accuracy: 0.4500
Epoch 198/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6812 - accuracy: 0.4500
Epoch 199/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6809 - accuracy: 0.4500
Epoch 200/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6806 - accuracy: 0.4500
Epoch 201/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6803 - accuracy: 0.4500
Epoch 202/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6799 - accuracy: 0.4500
Epoch 203/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6796 - accuracy: 0.4500

In [8]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 168ms/step - loss: 0.5623 - accuracy: 0.8333

[0.562300443649292, 0.8333333134651184]

In [9]:
model.predict(X_test_scaled) #more than 0.5 means he will buy the insurance

1/1 [==============================] - 0s 57ms/step

array([[0.65371585],
       [0.62825775],
       [0.64442956],
       [0.43246832],
       [0.6641867 ],
       [0.41965082]], dtype=float32)

In [10]:
X_test_scaled

     age  affordability
2   0.47              1
10  0.28              1
21  0.40              1
11  0.27              0
14  0.55              1
9   0.18              0

In [11]:
coef,intercept = model.get_weights() #using tensorflow function!!!
coef,intercept

(array([[0.58243793],
        [0.7907129 ]], dtype=float32),
 array([-0.42904574], dtype=float32))

In [12]:
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [13]:
def prediction_function(age,affordability):
    weighted_sum= coef[0]*age+ coef[1]*affordability +intercept
    return sigmoid(weighted_sum)

In [14]:
prediction_function(0.47,1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_38044\4182413728.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))

0.6537158262135281

In [15]:

def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [16]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [39]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_threshold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordability'],y, epochs, loss_threshold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordability'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_threshold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_threshold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [41]:
customModel= myNN()
customModel.fit(X_train_scaled, y_train, epochs=1000, loss_threshold=0.3831)

Epoch:0, w1:0.9417429336237633, w2:0.9598996358150476, bias:-0.16004975281869202, loss:0.7633872499715488
Epoch:50, w1:0.6060686808123442, w2:2.020345448505245, bias:-1.8348868363445705, loss:0.45240151349266433
Epoch:100, w1:0.7190365469628195, w2:2.7178083052742927, bias:-2.459828235670774, loss:0.4154329666708284
Epoch:150, w1:0.900735893606065, w2:3.143604374789744, bias:-2.9063994311359393, loss:0.39857814157661764
Epoch:200, w1:1.1086275928433023, w2:3.4429260038697063, bias:-3.259953424820108, loss:0.3881610059598234
Epoch:233, w1:1.251302229923289, w2:3.5998230495873687, bias:-3.4607452771225478, loss:0.38296420591007296
Final weights and bias: w1: 1.251302229923289, w2: 3.5998230495873687, bias: -3.4607452771225478

In [42]:

coef, intercept

(array([[0.58243793],
        [0.7907129 ]], dtype=float32),
 array([-0.42904574], dtype=float32))

In [43]:

X_test_scaled

     age  affordability
2   0.47              1
10  0.28              1
21  0.40              1
11  0.27              0
14  0.55              1
9   0.18              0

In [44]:
customModel.predict(X_test_scaled)

2     0.674188
10    0.619975
21    0.654663
11    0.042173
14    0.695782
9     0.037851
dtype: float64

In [45]:
model.predict(X_test_scaled) //tensorflow

1/1 [==============================] - 0s 20ms/step

array([[0.65371585],
       [0.62825775],
       [0.64442956],
       [0.43246832],
       [0.6641867 ],
       [0.41965082]], dtype=float32)

In [ ]:
Above you can compare predictions from our own #custom model and tensoflow model. You will notice that predictions are almost same