In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("insurance_data.csv")
df.head()

   age  affordability  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              1                 1
4   46              1                 1

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df[['age','affordability']],df.bought_insurance,test_size=0.2,random_state=25)

In [6]:
len(X_train)

20

In [7]:
X_train_scaled= X_train.copy()
X_train_scaled['age']= X_train_scaled['age']/100

X_test_scaled= X_test.copy()
X_test_scaled['age']= X_test_scaled['age']/100

In [8]:
X_train_scaled

     age  affordability
0   0.22              1
13  0.49              1
6   0.60              1
17  0.19              1
23  0.50              1
19  0.21              1
24  0.54              0
16  0.58              1
20  0.26              0
3   0.52              1
7   0.62              0
1   0.25              0
5   0.55              0
25  0.23              1
8   0.61              0
18  0.18              0
12  0.29              1
22  0.45              1
15  0.25              0
4   0.46              1

In [18]:

model = keras.Sequential([
    keras.layers.Dense(
        1,
        input_shape=(2,),       
        activation='sigmoid',
        kernel_initializer='ones',
        bias_initializer='zeros'
    )
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_scaled,y_train,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 374ms/step - loss: 0.7634 - accuracy: 0.4000
Epoch 2/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7629 - accuracy: 0.4000
Epoch 3/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7624 - accuracy: 0.4000
Epoch 4/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7618 - accuracy: 0.4000
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7613 - accuracy: 0.4000
Epoch 6/500
1/1 [==============================] - 0s 0s/step - loss: 0.7608 - accuracy: 0.4000
Epoch 7/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7603 - accuracy: 0.4000
Epoch 8/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7598 - accuracy: 0.4000
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7593 - accuracy: 0.4000
Epoch 10/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7588 - accuracy: 0.4000
Epoch 11/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7583 - accuracy: 0.4000
Epoch 12/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7578 - accuracy: 0.4000
Epoch 13/500
1/1 [==============================] - 0s 0s/step - loss: 0.7572 - accuracy: 0.4000
Epoch 14/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7567 - accuracy: 0.4000
Epoch 15/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7562 - accuracy: 0.4000
Epoch 16/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7557 - accuracy: 0.4000
Epoch 17/500
1/1 [==============================] - 0s 0s/step - loss: 0.7552 - accuracy: 0.4000
Epoch 18/500
1/1 [==============================] - 0s 0s/step - loss: 0.7547 - accuracy: 0.4000
Epoch 19/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7542 - accuracy: 0.4000
Epoch 20/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7537 - accuracy: 0.4000
Epoch 21/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7532 - accuracy: 0.4000
Epoch 22/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7527 - accuracy: 0.4000
Epoch 23/500
1/1 [==============================] - 0s 0s/step - loss: 0.7522 - accuracy: 0.4000
Epoch 24/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7517 - accuracy: 0.4000
Epoch 25/500
1/1 [==============================] - 0s 0s/step - loss: 0.7512 - accuracy: 0.4000
Epoch 26/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7507 - accuracy: 0.4000
Epoch 27/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7502 - accuracy: 0.4000
Epoch 28/500
1/1 [==============================] - 0s 0s/step - loss: 0.7497 - accuracy: 0.4000
Epoch 29/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7493 - accuracy: 0.4000
Epoch 30/500
1/1 [==============================] - 0s 0s/step - loss: 0.7488 - accuracy: 0.4000
Epoch 31/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7483 - accuracy: 0.4000
Epoch 32/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7478 - accuracy: 0.4000
Epoch 33/500
1/1 [==============================] - 0s 0s/step - loss: 0.7473 - accuracy: 0.4000
Epoch 34/500
1/1 [==============================] - 0s 0s/step - loss: 0.7468 - accuracy: 0.4000
Epoch 35/500
1/1 [==============================] - 0s 0s/step - loss: 0.7463 - accuracy: 0.4000
Epoch 36/500
1/1 [==============================] - 0s 12ms/step - loss: 0.7458 - accuracy: 0.4000
Epoch 37/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7454 - accuracy: 0.4000
Epoch 38/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7449 - accuracy: 0.4000
Epoch 39/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7444 - accuracy: 0.4000
Epoch 40/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7439 - accuracy: 0.4000
Epoch 41/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7434 - accuracy: 0.4000
Epoch 42/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7430 - accuracy: 0.4000
Epoch 43/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7425 - accuracy: 0.4000
Epoch 44/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7420 - accuracy: 0.4000
Epoch 45/500
1/1 [==============================] - 0s 0s/step - loss: 0.7415 - accuracy: 0.4000
Epoch 46/500
1/1 [==============================] - 0s 0s/step - loss: 0.7410 - accuracy: 0.4000
Epoch 47/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7406 - accuracy: 0.4000
Epoch 48/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7401 - accuracy: 0.4000
Epoch 49/500
1/1 [==============================] - 0s 0s/step - loss: 0.7396 - accuracy: 0.4000
Epoch 50/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7392 - accuracy: 0.4000
Epoch 51/500
1/1 [==============================] - 0s 0s/step - loss: 0.7387 - accuracy: 0.4000
Epoch 52/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7382 - accuracy: 0.4000
Epoch 53/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7378 - accuracy: 0.4000
Epoch 54/500
1/1 [==============================] - 0s 0s/step - loss: 0.7373 - accuracy: 0.4000
Epoch 55/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7368 - accuracy: 0.4000
Epoch 56/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7364 - accuracy: 0.4000
Epoch 57/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7359 - accuracy: 0.4000
Epoch 58/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7354 - accuracy: 0.4000
Epoch 59/500
1/1 [==============================] - 0s 0s/step - loss: 0.7350 - accuracy: 0.4000
Epoch 60/500
1/1 [==============================] - 0s 0s/step - loss: 0.7345 - accuracy: 0.4000
Epoch 61/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7341 - accuracy: 0.4000
Epoch 62/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7336 - accuracy: 0.4000
Epoch 63/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7332 - accuracy: 0.4000
Epoch 64/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7327 - accuracy: 0.4000
Epoch 65/500
1/1 [==============================] - 0s 0s/step - loss: 0.7322 - accuracy: 0.4000
Epoch 66/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7318 - accuracy: 0.4000
Epoch 67/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7313 - accuracy: 0.4000
Epoch 68/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7309 - accuracy: 0.4000
Epoch 69/500
1/1 [==============================] - 0s 0s/step - loss: 0.7304 - accuracy: 0.4000
Epoch 70/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7300 - accuracy: 0.4000
Epoch 71/500
1/1 [==============================] - 0s 128us/step - loss: 0.7296 - accuracy: 0.4000
Epoch 72/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7291 - accuracy: 0.4000
Epoch 73/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7287 - accuracy: 0.4000
Epoch 74/500
1/1 [==============================] - 0s 0s/step - loss: 0.7282 - accuracy: 0.4000
Epoch 75/500
1/1 [==============================] - 0s 0s/step - loss: 0.7278 - accuracy: 0.4000
Epoch 76/500
1/1 [==============================] - 0s 0s/step - loss: 0.7273 - accuracy: 0.4000
Epoch 77/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7269 - accuracy: 0.4000
Epoch 78/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7265 - accuracy: 0.4000
Epoch 79/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7260 - accuracy: 0.4000
Epoch 80/500
1/1 [==============================] - 0s 0s/step - loss: 0.7256 - accuracy: 0.4000
Epoch 81/500
1/1 [==============================] - 0s 0s/step - loss: 0.7251 - accuracy: 0.4000
Epoch 82/500
1/1 [==============================] - 0s 507us/step - loss: 0.7247 - accuracy: 0.4000
Epoch 83/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7243 - accuracy: 0.4000
Epoch 84/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7238 - accuracy: 0.4000
Epoch 85/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7234 - accuracy: 0.4000
Epoch 86/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7230 - accuracy: 0.4000
Epoch 87/500
1/1 [==============================] - 0s 0s/step - loss: 0.7225 - accuracy: 0.4000
Epoch 88/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7221 - accuracy: 0.4000
Epoch 89/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7217 - accuracy: 0.4000
Epoch 90/500
1/1 [==============================] - 0s 0s/step - loss: 0.7213 - accuracy: 0.4000
Epoch 91/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7208 - accuracy: 0.4000
Epoch 92/500
1/1 [==============================] - 0s 0s/step - loss: 0.7204 - accuracy: 0.4000
Epoch 93/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7200 - accuracy: 0.4000
Epoch 94/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7196 - accuracy: 0.4000
Epoch 95/500
1/1 [==============================] - 0s 0s/step - loss: 0.7192 - accuracy: 0.4000
Epoch 96/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7187 - accuracy: 0.4000
Epoch 97/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7183 - accuracy: 0.4000
Epoch 98/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7179 - accuracy: 0.4000
Epoch 99/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7175 - accuracy: 0.4000
Epoch 100/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7171 - accuracy: 0.4000
Epoch 101/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7166 - accuracy: 0.4000
Epoch 102/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7162 - accuracy: 0.4000
Epoch 103/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7158 - accuracy: 0.4000
Epoch 104/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7154 - accuracy: 0.4000
Epoch 105/500
1/1 [==============================] - 0s 0s/step - loss: 0.7150 - accuracy: 0.4000
Epoch 106/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7146 - accuracy: 0.4000
Epoch 107/500
1/1 [==============================] - 0s 0s/step - loss: 0.7142 - accuracy: 0.4000
Epoch 108/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7138 - accuracy: 0.4000
Epoch 109/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7134 - accuracy: 0.4000
Epoch 110/500
1/1 [==============================] - 0s 0s/step - loss: 0.7130 - accuracy: 0.4000
Epoch 111/500
1/1 [==============================] - 0s 0s/step - loss: 0.7126 - accuracy: 0.4000
Epoch 112/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7122 - accuracy: 0.4000
Epoch 113/500
1/1 [==============================] - 0s 0s/step - loss: 0.7118 - accuracy: 0.4000
Epoch 114/500
1/1 [==============================] - 0s 0s/step - loss: 0.7114 - accuracy: 0.4000
Epoch 115/500
1/1 [==============================] - 0s 0s/step - loss: 0.7110 - accuracy: 0.4000
Epoch 116/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7106 - accuracy: 0.4000
Epoch 117/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7102 - accuracy: 0.4000
Epoch 118/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7098 - accuracy: 0.4000
Epoch 119/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7094 - accuracy: 0.4000
Epoch 120/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7090 - accuracy: 0.4000
Epoch 121/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7086 - accuracy: 0.4000
Epoch 122/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7082 - accuracy: 0.4000
Epoch 123/500
1/1 [==============================] - 0s 6ms/step - loss: 0.7078 - accuracy: 0.4000
Epoch 124/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7074 - accuracy: 0.4000
Epoch 125/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7070 - accuracy: 0.4000
Epoch 126/500
1/1 [==============================] - 0s 0s/step - loss: 0.7066 - accuracy: 0.4000
Epoch 127/500
1/1 [==============================] - 0s 0s/step - loss: 0.7062 - accuracy: 0.4000
Epoch 128/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7058 - accuracy: 0.4000
Epoch 129/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7055 - accuracy: 0.4000
Epoch 130/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7051 - accuracy: 0.4000
Epoch 131/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7047 - accuracy: 0.4000
Epoch 132/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7043 - accuracy: 0.4000
Epoch 133/500
1/1 [==============================] - 0s 0s/step - loss: 0.7039 - accuracy: 0.4000
Epoch 134/500
1/1 [==============================] - 0s 0s/step - loss: 0.7035 - accuracy: 0.4000
Epoch 135/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7032 - accuracy: 0.4000
Epoch 136/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7028 - accuracy: 0.4000
Epoch 137/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7024 - accuracy: 0.4000
Epoch 138/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7020 - accuracy: 0.4000
Epoch 139/500
1/1 [==============================] - 0s 11ms/step - loss: 0.7017 - accuracy: 0.4000
Epoch 140/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7013 - accuracy: 0.4000
Epoch 141/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7009 - accuracy: 0.4000
Epoch 142/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7005 - accuracy: 0.4000
Epoch 143/500
1/1 [==============================] - 0s 8ms/step - loss: 0.7002 - accuracy: 0.4000
Epoch 144/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6998 - accuracy: 0.4000
Epoch 145/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6994 - accuracy: 0.4000
Epoch 146/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6991 - accuracy: 0.4000
Epoch 147/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6987 - accuracy: 0.4000
Epoch 148/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6983 - accuracy: 0.4000
Epoch 149/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6980 - accuracy: 0.4000
Epoch 150/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6976 - accuracy: 0.4000
Epoch 151/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6972 - accuracy: 0.4000
Epoch 152/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6969 - accuracy: 0.4000
Epoch 153/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6965 - accuracy: 0.4000
Epoch 154/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6961 - accuracy: 0.4000
Epoch 155/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6958 - accuracy: 0.4000
Epoch 156/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6954 - accuracy: 0.4000
Epoch 157/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6951 - accuracy: 0.4000
Epoch 158/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6947 - accuracy: 0.4000
Epoch 159/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6944 - accuracy: 0.4000
Epoch 160/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6940 - accuracy: 0.4500
Epoch 161/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6936 - accuracy: 0.4500
Epoch 162/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6933 - accuracy: 0.4500
Epoch 163/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6929 - accuracy: 0.4500
Epoch 164/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6926 - accuracy: 0.4500
Epoch 165/500
1/1 [==============================] - 0s 0s/step - loss: 0.6922 - accuracy: 0.4500
Epoch 166/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6919 - accuracy: 0.4500
Epoch 167/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6915 - accuracy: 0.4500
Epoch 168/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6912 - accuracy: 0.4500
Epoch 169/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6909 - accuracy: 0.4500
Epoch 170/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6905 - accuracy: 0.4500
Epoch 171/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6902 - accuracy: 0.4500
Epoch 172/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6898 - accuracy: 0.4500
Epoch 173/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6895 - accuracy: 0.4500
Epoch 174/500
1/1 [==============================] - 0s 0s/step - loss: 0.6891 - accuracy: 0.4500
Epoch 175/500
1/1 [==============================] - 0s 1ms/step - loss: 0.6888 - accuracy: 0.4500
Epoch 176/500
1/1 [==============================] - 0s 734us/step - loss: 0.6885 - accuracy: 0.4500
Epoch 177/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6881 - accuracy: 0.4500
Epoch 178/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6878 - accuracy: 0.4500
Epoch 179/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6874 - accuracy: 0.4500
Epoch 180/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6871 - accuracy: 0.4500
Epoch 181/500
1/1 [==============================] - 0s 0s/step - loss: 0.6868 - accuracy: 0.4500
Epoch 182/500
1/1 [==============================] - 0s 249us/step - loss: 0.6864 - accuracy: 0.4500
Epoch 183/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.4500
Epoch 184/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6858 - accuracy: 0.4500
Epoch 185/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6854 - accuracy: 0.4500
Epoch 186/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6851 - accuracy: 0.4500
Epoch 187/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6848 - accuracy: 0.4500
Epoch 188/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6845 - accuracy: 0.4500
Epoch 189/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6841 - accuracy: 0.4500
Epoch 190/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6838 - accuracy: 0.4500
Epoch 191/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6835 - accuracy: 0.4500
Epoch 192/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6831 - accuracy: 0.4500
Epoch 193/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6828 - accuracy: 0.4500
Epoch 194/500
1/1 [==============================] - 0s 0s/step - loss: 0.6825 - accuracy: 0.4500
Epoch 195/500
1/1 [==============================] - 0s 592us/step - loss: 0.6822 - accuracy: 0.4500
Epoch 196/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6819 - accuracy: 0.4500
Epoch 197/500
1/1 [==============================] - 0s 0s/step - loss: 0.6815 - accuracy: 0.4500
Epoch 198/500
1/1 [==============================] - 0s 0s/step - loss: 0.6812 - accuracy: 0.4500
Epoch 199/500
1/1 [==============================] - 0s 3ms/step - loss: 0.6809 - accuracy: 0.4500
Epoch 200/500
1/1 [==============================] - 0s 8ms/step - loss: 0.6806 - accuracy: 0.4500
Epoch 201/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6803 - accuracy: 0.4500
Epoch 202/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6799 - accuracy: 0.4500
Epoch 203/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6796 - accuracy: 0.4500
Epoch 204/500

In [19]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 177ms/step - loss: 0.5623 - accuracy: 0.8333

[0.562300443649292, 0.8333333134651184]

In [20]:
model.predict(X_test_scaled) #more than 0.5 means he will buy the insurance

1/1 [==============================] - 0s 129ms/step

array([[0.65371585],
       [0.62825775],
       [0.64442956],
       [0.43246832],
       [0.6641867 ],
       [0.41965082]], dtype=float32)

In [21]:
X_test_scaled

     age  affordability
2   0.47              1
10  0.28              1
21  0.40              1
11  0.27              0
14  0.55              1
9   0.18              0

In [23]:
coef,intercept = model.get_weights() #using tensorflow function!!!
coef,intercept

(array([[0.58243793],
        [0.7907129 ]], dtype=float32),
 array([-0.42904574], dtype=float32))

In [30]:
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))

In [31]:
def prediction_function(age,affordability):
    weighted_sum= coef[0]*age+ coef[1]*affordability +intercept
    return sigmoid(weighted_sum)

In [32]:
prediction_function(0.47,1)

C:\Users\Dell\AppData\Local\Temp\ipykernel_27628\4182413728.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))

0.6537158262135281

In [33]:

def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [34]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [35]:
def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [42]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordability'],y_train,4000, 0.3651)

Epoch:0, w1:0.9417429336237633, w2:0.9598996358150476, bias:-0.16004975281869202, loss:0.7633872499715488
Epoch:1, w1:0.8915589178332827, w2:0.9311342163772272, bias:-0.29987918139400804, loss:0.7062511850385205
Epoch:2, w1:0.848830638420335, w2:0.9130339023510808, bias:-0.4211305148209427, loss:0.663699671036478
Epoch:3, w1:0.8127364929867725, w2:0.9045014311242385, bias:-0.5259238600843001, loss:0.6324246470332372
Epoch:4, w1:0.7823807208673199, w2:0.9042322918491189, bias:-0.6165357393850078, loss:0.6094664629237819
Epoch:5, w1:0.7568891902099442, w2:0.9108921899734166, bias:-0.6951670662332271, loss:0.5924345564785555
Epoch:6, w1:0.7354653668250947, w2:0.9232303297315658, bias:-0.7638107461094875, loss:0.5795308000606487
Epoch:7, w1:0.7174145482376012, w2:0.9401363212799361, bias:-0.8241970456249407, loss:0.5694671501397951
Epoch:8, w1:0.7021477259459787, w2:0.9606584178928229, bias:-0.8777880239694975, loss:0.5613505511423982
Epoch:9, w1:0.6891744911389016, w2:0.9839994457384778, bias:-0.9257978038662807, loss:0.5545746640469381
Epoch:10, w1:0.6780912147007926, w2:1.009501924283083, bias:-0.9692235602432708, loss:0.5487329926882919
Epoch:11, w1:0.6685680693203709, w2:1.0366293027988556, bias:-1.0088787001914452, loss:0.54355479980352
Epoch:12, w1:0.6603366905738428, w2:1.0649470205901923, bias:-1.0454240245034705, loss:0.5388600959751106
Epoch:13, w1:0.6531792379245068, w2:1.094105135478703, bias:-1.0793951527664385, loss:0.5345289539402236
Epoch:14, w1:0.6469190652840648, w2:1.1238231746578184, bias:-1.1112258010774407, loss:0.5304809720595135
Epoch:15, w1:0.6414129442330228, w2:1.1538773035579348, bias:-1.1412671210061596, loss:0.52666168721943
Epoch:16, w1:0.6365446714686694, w2:1.184089649498841, bias:-1.1698035581257547, loss:0.5230336489257864
Epoch:17, w1:0.6322198595928421, w2:1.2143195170550254, bias:-1.1970657521236148, loss:0.5195705802241781
Epoch:18, w1:0.6283617152629537, w2:1.2444562117775535, bias:-1.22324097808395, loss:0.5162535667782068
Epoch:19, w1:0.6249076291979622, w2:1.2744132053658235, bias:-1.2484815716513238, loss:0.5130685720804775
Epoch:20, w1:0.6218064276891652, w2:1.304123406369706, bias:-1.2729117147985636, loss:0.5100048172596712
Epoch:21, w1:0.6190161600383831, w2:1.3335353350355332, bias:-1.296632895421857, loss:0.5070537236588293
Epoch:22, w1:0.6165023186201325, w2:1.3626100338984226, bias:-1.3197282975946871, loss:0.5042082214404909
Epoch:23, w1:0.6142364073843155, w2:1.3913185751012138, bias:-1.3422663312811252, loss:0.5014622962139574
Epoch:24, w1:0.6121947906036728, w2:1.4196400506126587, bias:-1.364303470357399, loss:0.49881069048896487
Epoch:25, w1:0.6103577668306882, w2:1.4475599526470349, bias:-1.3858865350271712, loss:0.49624870590846404
Epoch:26, w1:0.6087088237568886, w2:1.4750688690673155, bias:-1.4070545280806555, loss:0.49377207115212485
Epoch:27, w1:0.6072340383592341, w2:1.5021614328873714, bias:-1.4278401129124914, loss:0.49137685270047227
Epoch:28, w1:0.6059215937322222, w2:1.5288354766730636, bias:-1.448270803861794, loss:0.48905939363419515
Epoch:29, w1:0.6047613896497317, w2:1.5550913521292868, bias:-1.4683699254879583, loss:0.4868162708275313
Epoch:30, w1:0.6037447284369353, w2:1.5809313828421017, bias:-1.488157386196285, loss:0.48464426426163776
Epoch:31, w1:0.6028640613737912, w2:1.6063594243536397, bias:-1.5076503026437393, loss:0.4825403343713222
Epoch:32, w1:0.6021127837723572, w2:1.6313805107584267, bias:-1.526863504152361, loss:0.48050160476026915
Epoch:33, w1:0.6014850692121045, w2:1.656000571050414, bias:-1.5458099405843844, loss:0.47852534854439976
Epoch:34, w1:0.6009757352949024, w2:1.680226201706194, bias:-1.5645010125057428, loss:0.47660897718446715
Epoch:35, w1:0.6005801347864502, w2:1.704064484612874, bias:-1.5829468387555905, loss:0.4747500310605025
Epoch:36, w1:0.600294067217613, w2:1.7275228415615456, bias:-1.6011564735660972, loss:0.4729461712957053
Epoch:37, w1:0.6001137069867111, w2:1.7506089182284659, bias:-1.619138082992605, loss:0.4711951725035576
Epoch:38, w1:0.6000355447798755, w2:1.7733304919360773, bias:-1.6368990885019472, loss:0.46949491624032513
Epoch:39, w1:0.6000563397492226, w2:1.7956953985894413, bias:-1.654446284032432, loss:0.46784338501587996
Epoch:40, w1:0.6001730803883177, w2:1.8177114750726042, bias:-1.6717859316074568, loss:0.46623865676204784
Epoch:41, w1:0.6003829524456369, w2:1.83938651410573, bias:-1.688923839595818, loss:0.4646788996880059
Epoch:42, w1:0.6006833125390181, w2:1.8607282291412361, bias:-1.7058654269173241, loss:0.4631623674721899
Epoch:43, w1:0.6010716663931064, w2:1.8817442273427736, bias:-1.722615775853762, loss:0.4616873947533275
Epoch:44, w1:0.601545650830043, w2:1.9024419890664677, bias:-1.7391796756117672, loss:0.4602523928919788
Epoch:45, w1:0.602103018811178, w2:1.9228288525669603, bias:-1.7555616583709774, loss:0.4588558459798439
Epoch:46, w1:0.6027416269624325, w2:1.9429120028955096, bias:-1.771766029218215, loss:0.45749630707811695
Epoch:47, w1:0.6034594251245304, w2:1.9626984641550893, bias:-1.7877968911005104, loss:0.45617239466895765
Epoch:48, w1:0.604254447556837, w2:1.9821950944371791, bias:-1.8036581657138109, loss:0.4548827893061517
Epoch:49, w1:0.6051248054941025, w2:2.0014085828941024, bias:-1.8193536110700341, loss:0.4536262304525073
Epoch:50, w1:0.6060686808123442, w2:2.020345448505245, bias:-1.8348868363445705, loss:0.45240151349266433
Epoch:51, w1:0.6070843206060664, w2:2.039012040180042, bias:-1.8502613144928093, loss:0.45120748691090107
Epoch:52, w1:0.6081700325161548, w2:2.0574145379090836, bias:-1.8654803930325383, loss:0.45004304962426794
Epoch:53, w1:0.6093241806778014, w2:2.0755589547301216, bias:-1.8805473033148827, loss:0.4489071484620288
Epoch:54, w1:0.6105451821821115, w2:2.093451139320715, bias:-1.895465168546421, loss:0.44779877578295063
Epoch:55, w1:0.6118315039647021, w2:2.1110967790656505, bias:-1.910237010776499, loss:0.44671696722250376
Epoch:56, w1:0.6131816600505404, w2:2.1285014034768195, bias:-1.9248657570243688, loss:0.4456607995625036
Epoch:57, w1:0.6145942090971879, w2:2.1456703878671815, bias:-1.9393542446888208, loss:0.4446293887161638
Epoch:58, w1:0.6160677521891, w2:2.1626089571998746, bias:-1.9537052263570427, loss:0.4436218878219417
Epoch:59, w1:0.6176009308441494, w2:2.1793221900493025, bias:-1.9679213741083648, loss:0.44263748543993675
Epoch:60, w1:0.6191924252004603, w2:2.1958150226238105, bias:-1.9820052833914177, loss:0.4416754038449766
Epoch:61, w1:0.6208409523572793, w2:2.21209225280995, bias:-1.9959594765392843, loss:0.44073489741085226
Epoch:62, w1:0.6225452648481912, w2:2.2281585442067415, bias:-2.0097864059758694, loss:0.43981525108050323
Epoch:63, w1:0.6243041492287336, w2:2.2440184301251658, bias:-2.023488457157445, loss:0.43891577891724365
Epoch:64, w1:0.6261164247635165, w2:2.2596763175336547, bias:-2.037067951285771, loss:0.43803582273242025
Epoch:65, w1:0.6279809422004493, w2:2.2751364909348135, bias:-2.050527147823004, loss:0.43717475078515494
Epoch:66, w1:0.6298965826217194, w2:2.290403116162241, bias:-2.0638682468335627, loss:0.43633195655009044
Epoch:67, w1:0.6318622563628429, w2:2.3054802440892272, bias:-2.077093391173963, loss:0.43550685754928653
Epoch:68, w1:0.6338769019924791, w2:2.320371814243469, bias:-2.0902046685482385, loss:0.43469889424465513
Epoch:69, w1:0.6359394853468334, w2:2.335081658323838, bias:-2.103204113443777, loss:0.43390752898752555
Epoch:70, w1:0.6380489986133991, w2:2.3496135036167556, bias:-2.1160937089600944, loss:0.43313224502213793
Epoch:71, w1:0.6402044594595627, w2:2.363970976310938, bias:-2.128875388541179, loss:0.4323725455400515
Epoch:72, w1:0.6424049102022269, w2:2.3781576047102435, bias:-2.141551037620462, loss:0.4316279527826305
Epoch:73, w1:0.6446494170151352, w2:2.392176822345116, bias:-2.154122495186188, loss:0.43089800718894145
Epoch:74, w1:0.6469370691710209, w2:2.4060319709837086, bias:-2.1665915552738704, loss:0.4301822665865468
Epoch:75, w1:0.6492669783160641, w2:2.4197263035442416, bias:-2.178959968391624, loss:0.42948030542283566
Epoch:76, w1:0.6516382777744514, w2:2.4332629869105027, bias:-2.1912294428834262, loss:0.42879171403466454
Epoch:77, w1:0.6540501218810855, w2:2.446645104652656, bias:-2.203401646234721, loss:0.4281160979542121
Epoch:78, w1:0.6565016853407085, w2:2.45987565965573, bias:-2.2154782063242657, loss:0.4274530772490814
Epoch:79, w1:0.6589921626118873, w2:2.4729575766582856, bias:-2.2274607126256742, loss:0.4268022858947858
Epoch:80, w1:0.6615207673144627, w2:2.485893704703862, bias:-2.2393507173617295, loss:0.42616337117787717
Epoch:81, w1:0.6640867316591974, w2:2.4986868195078413, bias:-2.2511497366142335, loss:0.4255359931280617
Epoch:82, w1:0.6666893058984723, w2:2.5113396257424094, bias:-2.262859251391879, loss:0.42491982397775646
Epoch:83, w1:0.6693277577969768, w2:2.5238547592422766, bias:-2.274480708658404, loss:0.42431454764762355
Epoch:84, w1:0.6720013721214265, w2:2.5362347891338133, bias:-2.2860155223230816, loss:0.42371985925669914
Epoch:85, w1:0.6747094501484131, w2:2.548482219890219, bias:-2.2974650741954346, loss:0.42313546465582486
Epoch:86, w1:0.6774513091895586, w2:2.5605994933152907, bias:-2.308830714905902, loss:0.4225610799831486
Epoch:87, w1:0.6802262821332021, w2:2.572588990458317, bias:-2.320113764794062, loss:0.4219964312405463
Epoch:88, w1:0.6830337170018982, w2:2.5844530334625473, bias:-2.3313155147658975, loss:0.42144125388986897
Epoch:89, w1:0.6858729765250522, w2:2.596193887349637, bias:-2.342437227121482, loss:0.42089529246798946
Epoch:90, w1:0.6887434377260584, w2:2.607813761742385, bias:-2.3534801363543827, loss:0.4203583002196788
Epoch:91, w1:0.6916444915233423, w2:2.6193148125280246, bias:-2.3644454499239864, loss:0.41983003874739244
Epoch:92, w1:0.6945755423447438, w2:2.630699143464245, bias:-2.3753343490018866, loss:0.4193102776771062
Epoch:93, w1:0.6975360077547073, w2:2.641968807730056, bias:-2.3861479891934, loss:0.418798794339381
Epoch:94, w1:0.7005253180937715, w2:2.6531258094235337, bias:-2.3968875012352244, loss:0.4182953734648865
Epoch:95, w1:0.7035429161298812, w2:2.6641721050084133, bias:-2.4075539916701927, loss:0.41779980689365487
Epoch:96, w1:0.706588256721061, w2:2.675109604711428, bias:-2.4181485435000254, loss:0.4173118932973748
Epoch:97, w1:0.7096608064890187, w2:2.6859401738722197, bias:-2.428672216816942, loss:0.41683143791407495
Epoch:98, w1:0.7127600435032635, w2:2.696665634247585, bias:-2.4391260494149476, loss:0.4163582522945811
Epoch:99, w1:0.7158854569753423, w2:2.7072877652717477, bias:-2.4495110573815677, loss:0.415892154060164
Epoch:100, w1:0.7190365469628195, w2:2.7178083052742927, bias:-2.459828235670774, loss:0.4154329666708284
Epoch:101, w1:0.7222128240826365, w2:2.7282289526573287, bias:-2.4700785586578022, loss:0.41498051920372026
Epoch:102, w1:0.725413809233509, w2:2.7385513670333896, bias:-2.4802629806765397, loss:0.41453464614116087
Epoch:103, w1:0.7286390333270295, w2:2.7487771703255253, bias:-2.4903824365401177, loss:0.4140951871678385
Epoch:104, w1:0.7318880370271614, w2:2.758907947830977, bias:-2.5004378420453293, loss:0.4136619869767184
Epoch:105, w1:0.7351603704978203, w2:2.7689452492497812, bias:-2.510430094461457, loss:0.41323489508324907
Epoch:106, w1:0.7384555931582532, w2:2.778890589679585, bias:-2.5203600730040727, loss:0.4128137656474705
Epoch:107, w1:0.7417732734459376, w2:2.7887454505779172, bias:-2.5302286392943487, loss:0.4123984573036485
Epoch:108, w1:0.745112988586734, w2:2.7985112806931074, bias:-2.5400366378043926, loss:0.41198883299707667
Epoch:109, w1:0.7484743243720352, w2:2.808189496964986, bias:-2.549784896289105, loss:0.4115847598277105
Epoch:110, w1:0.7518568749426668, w2:2.817781485396479, bias:-2.5594742262050323, loss:0.41118610890031243
Epoch:111, w1:0.7552602425793046, w2:2.827288601897144, bias:-2.5691054231166666, loss:0.41079275518080405
Epoch:112, w1:0.7586840374991795, w2:2.8367121730996643, bias:-2.5786792670906316, loss:0.41040457735853736
Epoch:113, w1:0.762127877658856, w2:2.8460534971502818, bias:-2.588196523078175, loss:0.41002145771421167
Epoch:114, w1:0.7655913885628723, w2:2.8553138444740975, bias:-2.5976579412863656, loss:0.40964328199317646
Epoch:115, w1:0.7690742030780421, w2:2.8644944585161474, bias:-2.6070642575383847, loss:0.40926993928387373
Epoch:116, w1:0.7725759612532253, w2:2.8735965564591166, bias:-2.6164161936232815, loss:0.4089013219011862
Epoch:117, w1:0.7760963101443817, w2:2.882621329918525, bias:-2.6257144576355507, loss:0.40853732527446845
Epoch:118, w1:0.7796349036447295, w2:2.891569945616182, bias:-2.6349597443048727, loss:0.40817784784005007
Epoch:119, w1:0.783191402319835, w2:2.9004435460326823, bias:-2.6441527353163514, loss:0.40782279093801127
Epoch:120, w1:0.7867654732474707, w2:2.9092432500396797, bias:-2.6532940996215606, loss:0.40747205871303754
Epoch:121, w1:0.7903567898620819, w2:2.9179701535126505, bias:-2.662384493740708, loss:0.4071255580191747
Epoch:122, w1:0.7939650318037073, w2:2.926625329924828, bias:-2.6714245620562123, loss:0.40678319832831045
Epoch:123, w1:0.7975898847712084, w2:2.9352098309229677, bias:-2.680414937097968, loss:0.40644489164221964
Epoch:124, w1:0.801231040379665, w2:2.9437246868855738, bias:-2.6893562398205826, loss:0.4061105524080141
Epoch:125, w1:0.804888196021799, w2:2.9521709074641937, bias:-2.698249079872837, loss:0.4057800974368531
Epoch:126, w1:0.8085610547332975, w2:2.9605494821083664, bias:-2.707094055859625, loss:0.40545344582576953
Epoch:127, w1:0.8122493250619062, w2:2.968861380574785, bias:-2.7158917555966187, loss:0.40513051888247825
Epoch:128, w1:0.8159527209401716, w2:2.9771075534212184, bias:-2.724642756357889, loss:0.4048112400530397
Epoch:129, w1:0.8196709615617157, w2:2.985288932485706, bias:-2.7333476251167075, loss:0.40449553485225326
Epoch:130, w1:0.8234037712609278, w2:2.993406431351535, bias:-2.7420069187797513, loss:0.4041833307966699
Epoch:131, w1:0.8271508793959654, w2:3.0014609457984727, bias:-2.750621184414914, loss:0.40387455734010597
Epoch:132, w1:0.830912020234959, w2:3.0094533542407236, bias:-2.7591909594729307, loss:0.40356914581155967
Epoch:133, w1:0.834686932845318, w2:3.0173845181520584, bias:-2.7677167720030065, loss:0.403267029355424
Epoch:134, w1:0.8384753609860416, w2:3.0252552824785415, bias:-2.776199140862643, loss:0.4029681428739032
Epoch:135, w1:0.8422770530029384, w2:3.033066476039272, bias:-2.7846385759218357, loss:0.40267242297154054
Epoch:136, w1:0.8460917617266654, w2:3.0408189119155375, bias:-2.793035578261824, loss:0.4023798079017693
Epoch:137, w1:0.8499192443734969, w2:3.048513387828766, bias:-2.8013906403685587, loss:0.4020902375154047
Epoch:138, w1:0.853759262448739, w2:3.0561506865076398, bias:-2.809704246321052, loss:0.401803653210996
Epoch:139, w1:0.8576115816527097, w2:3.0637315760447357, bias:-2.8179768719747633, loss:0.40151999788696485
Epoch:140, w1:0.8614759717892019, w2:3.0712568102430287, bias:-2.8262089851401777, loss:0.4012392158954542
Epoch:141, w1:0.8653522066763571, w2:3.0787271289525906, bias:-2.834401045756719, loss:0.40096125299782254
Epoch:142, w1:0.8692400640598735, w2:3.0861432583978057, bias:-2.8425535060621407, loss:0.40068605632171367
Epoch:143, w1:0.8731393255284781, w2:3.0935059114954044, bias:-2.8506668107575313, loss:0.400413574319641
Epoch:144, w1:0.8770497764315951, w2:3.1008157881636187, bias:-2.858741397168063, loss:0.4001437567290262
Epoch:145, w1:0.8809712057991438, w2:3.108073575622737, bias:-2.8667776953996174, loss:0.3998765545336323
Epoch:146, w1:0.8849034062634009, w2:3.1152799486873377, bias:-2.8747761284914035, loss:0.3996119199263387
Epoch:147, w1:0.8888461739828675, w2:3.1224355700504667, bias:-2.882737112564692, loss:0.3993498062732043
Epoch:148, w1:0.8927993085680793, w2:3.1295410905600134, bias:-2.8906610569677795, loss:0.39909016807876724
Epoch:149, w1:0.8967626130093034, w2:3.1365971494875313, bias:-2.8985483644172927, loss:0.39883296095253506
Epoch:150, w1:0.900735893606065, w2:3.143604374789744, bias:-2.9063994311359393, loss:0.39857814157661764
Epoch:151, w1:0.9047189598984511, w2:3.150563383362962, bias:-2.914214646986814, loss:0.39832566767445976
Epoch:152, w1:0.9087116246001381, w2:3.157474781290636, bias:-2.921994395604353, loss:0.3980754979806298
Epoch:153, w1:0.9127137035330938, w2:3.164339164084259, bias:-2.9297390545220368, loss:0.39782759221162556
Epoch:154, w1:0.9167250155639042, w2:3.171157116917821, bias:-2.9374489952969394, loss:0.39758191103765744
Epoch:155, w1:0.9207453825416789, w2:3.177929214856019, bias:-2.945124583631208, loss:0.3973384160553721
Epoch:156, w1:0.9247746292374891, w2:3.1846560230764114, bias:-2.9527661794905646, loss:0.39709706976148174
Epoch:157, w1:0.9288125832852935, w2:3.191338097085707, bias:-2.9603741372199126, loss:0.39685783552726395
Epoch:158, w1:0.9328590751243109, w2:3.197975982930362, bias:-2.967948805656133, loss:0.3966206775739002
Epoch:159, w1:0.936913937942797, w2:3.2045702174016615, bias:-2.975490528238149, loss:0.3963855609486217
Epoch:160, w1:0.940977007623186, w2:3.2111213282354525, bias:-2.9829996431143315, loss:0.3961524515016325
Epoch:161, w1:0.9450481226885584, w2:3.2176298343066883, bias:-2.9904764832473294, loss:0.3959213158637807
Epoch:162, w1:0.949127124250397, w2:3.2240962458189424, bias:-2.9979213765163863, loss:0.39569212142495164
Epoch:163, w1:0.9532138559575962, w2:3.23052106448904, bias:-3.0053346458172214, loss:0.39546483631315443
Epoch:164, w1:0.9573081639466882, w2:3.2369047837269553, bias:-3.012716609159538, loss:0.3952394293742794
Epoch:165, w1:0.9614098967932527, w2:3.2432478888111143, bias:-3.0200675797622263, loss:0.39501587015249917
Epoch:166, w1:0.9655189054644778, w2:3.2495508570592353, bias:-3.0273878661463254, loss:0.3947941288712918
Epoch:167, w1:0.969635043272839, w2:3.255814157994848, bias:-3.0346777722258036, loss:0.3945741764150637
Epoch:168, w1:0.9737581658308668, w2:3.2620382535096075, bias:-3.041937597396217, loss:0.39435598431135
Epoch:169, w1:0.9778881310069725, w2:3.2682235980215335, bias:-3.049167636621305, loss:0.3941395247135723
Epoch:170, w1:0.9820247988823023, w2:3.27437063862929, bias:-3.056368180517582, loss:0.3939247703843337
Epoch:171, w1:0.9861680317085945, w2:3.280479815262623, bias:-3.0635395154369682, loss:0.39371169467923234
Epoch:172, w1:0.9903176938670084, w2:3.2865515608290616, bias:-3.070681923547527, loss:0.393500271531175
Epoch:173, w1:0.9944736518279029, w2:3.2925863013570007, bias:-3.0777956829123485, loss:0.3932904754351739
Epoch:174, w1:0.9986357741115364, w2:3.2985844561352575, bias:-3.0848810675666365, loss:0.393082281433608
Epoch:175, w1:1.002803931249664, w2:3.30454643784921, bias:-3.091938347593037, loss:0.39287566510193483
Epoch:176, w1:1.0069779957480085, w2:3.3104726527136124, bias:-3.0989677891952665, loss:0.39267060253483654
Epoch:177, w1:1.0111578420495826, w2:3.3163635006021828, bias:-3.1059696547700772, loss:0.3924670703327838
Epoch:178, w1:1.0153433464988366, w2:3.3222193751740523, bias:-3.1129442029776033, loss:0.3922650455890048
Epoch:179, w1:1.019534387306614, w2:3.3280406639971654, bias:-3.119891688810136, loss:0.39206450587684644
Epoch:180, w1:1.0237308445158908, w2:3.3338277486687176, bias:-3.1268123636593605, loss:0.39186542923750983
Epoch:181, w1:1.0279325999682785, w2:3.339581004932713, bias:-3.133706475382104, loss:0.39166779416815395
Epoch:182, w1:1.0321395372712723, w2:3.3453008027947195, bias:-3.1405742683646234, loss:0.391471579610349
Epoch:183, w1:1.0363515417662232, w2:3.350987506633903, bias:-3.14741598358548, loss:0.39127676493887137
Epoch:184, w1:1.040568500497016, w2:3.3566414753124136, bias:-3.1542318586770297, loss:0.3910833299508274
Epoch:185, w1:1.0447903021794358, w2:3.3622630622821963, bias:-3.1610221279855706, loss:0.3908912548550956
Epoch:186, w1:1.0490168371712032, w2:3.3678526156892987, bias:-3.167787022630176, loss:0.39070052026207563
Epoch:187, w1:1.0532479974426634, w2:3.3734104784757424, bias:-3.1745267705602536, loss:0.39051110717373494

(1.9918507704032924, 4.162915524759508, -4.279711243469651)

In [43]:
coef,intercept

(array([[0.58243793],
        [0.7907129 ]], dtype=float32),
 array([-0.42904574], dtype=float32))